### ISSUE TITLE
Fully document how to recreate a Kubernetes cluster for the AllenNLP demo

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-demo#116]

**Comment by gridcellcoder** [comment]
We've just had a stab at making the allennlp-demo work on  kubernetes Google Kubernetes Engine (GKE) Please feel free to use our implementation:

https://github.com/gridcellcoder/allennlp-demo/tree/gridcell-kubernetes
https://github.com/gridcellcoder/allennlp-demo/blob/gridcell-kubernetes/README.md

or get in touch and I can arrange a pull request.

**Comment by schmmd** [comment]
@gridcellcoder we run the AllenNLP demo on GKE.  Just curious, why were you working to make allennlp-demo run on GKE?

**Comment by schmmd** [comment]
Great to see this though--I've been meaning to try this out:

> allennlp.yml contains a StatefulSet that uses persistent volumes to store downloaded models on a disk attached to the node. This deployment is configured with 3 node replica.

@codeviking looks like someone else figured out how to get model caching working.  This is the basic approach I was considering.

**Comment by gridcellcoder** [comment]
> @gridcellcoder we run the AllenNLP demo on GKE. Just curious, why were you working to make allennlp-demo run on GKE?

> Great to see this though--I've been meaning to try this out:

Guess you answered your own question :smile: :  from our side to basically add the Kubernetes definitions to the repo and to test it out ourselves. Also we didn't know you were on GKE as I did not see the yaml files in the (master) repo, maybe it is on another branch?

Anyway hope it helps, we did a basic test of it but you guys are best to know more about caching the model etc.

**Comment by schmmd** [comment]
@gridcellcoder why do you want to run the AllenNLP demo?  Yes, we have an internal repository with the yaml configuration.

**Comment by gridcellcoder** [comment]
@schmmd we want to use the demo as a starting point for a REST api hosted on GKE which is available internally (for privacy reasons) to our organisation.

**Comment by schmmd** [comment]
We moved to skiff.
