### ISSUE TITLE
Re-organized the left pane to improve navigation

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-demo#118]
I'm currently thinking of changing the left pane to the following list (with sub-items):

- Annotate a passage.  This would allow sentences and paragraphs and includes Semantic Role Labeling, Coreference Resolution, Named Entity Recognition, Constituency Parsing, Dependency Parsing, and Open Information Extraction.

- Answer a question.  These each have different inputs so would be on separate pages.
  * Machine Comprehension
  * Semantic Parsing (Wikitables)
  * Semantic Parsing (Text2SQL)

- Other
  * Event2Mind

**Comment by schmmd** [comment]
@joelgrus we had discussed this previously.  What do you think of this organization?

**Comment by joelgrus** [comment]
is the rationale just to save space? feels like an artificial grouping?

**Comment by schmmd** [comment]
Motivation is twofold:

* Move away from an unmanageably long list (the current setup is hard for me to quickly peruse)
* Group similar models together and allow the user to get results from multiple models at the same time.

**Comment by joelgrus** [comment]
the second seems orthogonal to a menu change

I don't have strong feelings either way, I'd have to see how it looks

**Comment by schmmd** [comment]
I think it's worth trying out ;-)

Thanks for sharing your thoughts.

**Comment by schmmd** [comment]
Done.
