### ISSUE TITLE
New to AllenNLP. Trying to start the Demo.

### ISSUE THREAD

**Issue by Siddhant021295** [allenai/allennlp-demo#1208]
<img width="993" alt="image" src="https://user-images.githubusercontent.com/105399318/172403778-0e50ed0a-381a-4578-9a70-d0268df84d0d.png">

**Comment by Siddhant021295** [comment]
I am using an M1 Mac for someone help me with this issue?

**Comment by MHDBST** [comment]
I have the same issue. It seems that docker ps needs sudo permission. Is there any way to solve it?

**Comment by dirkgr** [comment]
Is this a new requirement in more recent versions of Docker?

It's not ideal, but can you run the whole thing like `sudo ./demo start`?

**Comment by dirkgr** [comment]
I'm closing this since it's a Docker issue, not a AllenNLP issue.
