### ISSUE TITLE
Emphasize that the AllenNLP library is losing support in December on allenai.org/allennlp.

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-demo#1218]
My thought is to simply reverse the order of the two software projects, but others might have better ideas.

**Comment by dirkgr** [comment]
I've wanted that order reversed since that website was created. It slipped through the cracks when I closed one too many tabs.

**Comment by schmmd** [comment]
![image](https://user-images.githubusercontent.com/954798/178371382-9fb474ae-ed9c-469f-aa0d-23f6df495e1a.png)

**Comment by isunitha98selvan** [comment]
Alternate idea: Module tabs with Tango (and catwalk?)  being under the default tab, the other tab could read archived and have the AllenNLP library.

**Comment by schmmd** [comment]
I will update this text:

> https://allenai.org/allennlp/software/allennlp-library

**Comment by schmmd** [comment]
> The AllenNLP library has been a big success at AI2 and beyond and has been used across the NLP field for state-of-the-art research.  However, as the field has been advancing fast, we have made the difficult decision to stop development on AllenNLP and instead focus on new initiatives that better fit current research, such as [AI2 Tango](https://allenai.org/allennlp/software/ai2-tango).

**Comment by schmmd** [comment]
Dirk added some alternatives to https://github.com/allenai/tango.
