### ISSUE TITLE
Notes from our call with AI2 Israel

### ISSUE THREAD

**Issue by codeviking** [allenai/allennlp-demo#133]
@jonborchardt and I met with AI2 Israel this morning.  This issue is meant to simply record notes from that call:

AI2 Israel's effort will deeply involve UI / UX development. They're at least a few months out from actually building an interface, but we're trying to gather some initial requirements.

* Graph / tree visualization.  Particularly w/ respect to sentence parsing and relationships within them. Could Hierplane be useful here? One immediate piece of feedback regarding Hierplane is that it's not very compact.
* The tool they're using now for tree visualization is preferable because of it's flexibility beyond trees (i.e. it can visualize relationships, etc).
* They'd like a template with unit-testing, tooling, common dependencies, etc already in place.  There was some mention of IKE and prior issues with it's development, as there was an impression that using React involved more complexity than it was worth.  I greatly understand this motivation, and would love to find a happy medium between the two alternatives.
* They're using `require`, `flask`, `jQuery`, etc right now. It's an acceptable setup, but they feel like it could be better.  They'd like direction soon.

**Comment by codeviking** [comment]
The biggest take away I have is that we need a template, and the template should support simple tool development.

We need to figure out how to handle the inevitable complexity that makes it way into SPAs as "stateful creep" occurs.

**Comment by codeviking** [comment]
They'd love any documentation / tutorials that'd be helpful in ramping up on the associated toolset.

**Comment by jonborchardt** [comment]
who:
hillel - research engineer
micah - research engineer intern 
yoav - research director
sam
jon

topics:
they are building relationship extraction based on rules
with workbench for development of rules

they are starting a new project that will be 'ui heavy'
want to see how we can be involved

in general, they want to
display graphs and trees of sentences in generic ways
currently using "brat" with json models
should they use higherplane? or spacy

they want/need some general ux guidance

what they are currently building, will be scrapped in a month what should they do after that do?

they are interested in general visualization of text data
summary of text, etc...

dirk is worked on something similar (ike) and suggested that react was not the right path
sam understands why, and we don't yet know if this reason applies to this situation
basic issue is that a growing react app needs to be written in correct ways to deal with scale... and if the team just tuck tapes it over and over, then react starts to not be the right choice (jonb's interpretation of what sam said) 

they asked for a simple project with modern tooling, unit testing, etc...

we should build 2 types of application templates for teams to jump from
dynamic react, and a non react

they are currently using basic js, flask and jquery, etc...

next steps:
send an email with some best practices and libs to look into
stay in touch

**Comment by codeviking** [comment]
Here's the tool they're using now:
http://brat.nlplab.org/

**Comment by codeviking** [comment]
They've been successful thus far in working on their tools and using Skiff.  We can close this until we hear from them again.
