### ISSUE TITLE
Visualize Augmented QAnet for the DROP leaderboard.

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-demo#134]
@matt-gardner would like to visualize his Augmented QAnet system in preparation for paper acceptance and the DROP leaderboard.  His system works on a similar task to the BiDAF demo we have at demo.allennlp.org but it does some reasoning to reach an answer.  The reasoning falls in the following categories:

1.  Arithmetic
2.  Counting
3.  Passage span (the answer exists in the passage)
4.  Question span (the answer exists in the question)

Presently the BiDAF demo always highlights all spans in the passage that matches the answer (essentially the proper visualization for 3 above).  Unfortunately, while there is occasionally something to highlight, this doesn't showcase how the model is coming to its answer.

Ideally we would have simple visualizations for 1, 2, and 3 to show how the model is reaching its conclusion.

**Comment by schmmd** [comment]
@matt-gardner would you post a screenshot with an example for 1 (arithmetic) and 2 (counting)?

**Comment by schmmd** [comment]
@matt-gardner or it might be easier to provide instructions for how to run your demo.  I'd play around with it a bit and also collect some helpful screenshots.

**Comment by matt-gardner** [comment]
If you're on the VPN, you can access it here: http://10.111.2.193:3000/machine-comprehension.

**Comment by schmmd** [comment]
## Arithmatic

Here's an example of the model performing some arithmetic to get it's answer.

**Passage**

> The total number of active military personnel in the Croatian Armed Forces stands at 14,506 and 6,000 reserves working in various service branches of the armed forces. In May 2016, Armed Forces had 16,019 members, of which 14,506 were active military personnel and XXX civil servants. Of the 14,506 active military personnel, 3,183 were officers, 5,389 non-commissioned officers, 5,393 soldiers, 520 military specialists, 337 civil servants and 1,176 other employees.

**Question**

> In May 2016, how many members of the Armed Forces were not active military personnel?

**Answer**

> 1513

**Reasoning**

16,019 - 14,506 = 1513

**Comment by schmmd** [comment]
@matt-gardner how do you understand the reasoning your model is doing presently?  I imagine you have some low-level (json?) output that you interpret.  Would you be able to give us an example?

**Comment by schmmd** [comment]
@matt-gardner separately could you highlight a counting example?  I didn't see one when I tried out the demo, although it was easy to find examples for the other cases.

**Comment by matt-gardner** [comment]
## Counting

There currently isn't anything to visualize here, except to separate it out as the model predicted this was a count.

**Passage**

> Hoping to rebound from their home loss to the Chiefs, the Raiders flew to Qualcomm Stadium for a Week 14 AFC West rematch with the San Diego Chargers.  In the first quarter, Oakland trailed early as Chargers kicker Nate Kaeding getting a 20-yard field goal, along with RB LaDainian Tomlinson getting a 3-yard TD run.  The Raiders continued to trail as QB Philip Rivers completed an 8-yard TD pass to RB Darren Sproles and a 59-yard TD pass to WR Vincent Jackson, while Kaeding got a 39-yard field goal.  Oakland responded with CB Justin Miller returning a kickoff 98 yards for a touchdown.  After a scoreless third quarter, San Diego pulled away in the fourth quarter as Rivers hooked up with Sproles again on an 18-yard TD pass. With the loss, not only did the Raiders fall to 3-10, but they also suffered their sixth-straight 10-loss season.

**Question**

> How many touchdowns did the Chargers score?

**Answer**

> 4

**Reasoning**

> The system predicted this was a counting question, with an answer of 4.

**Comment by matt-gardner** [comment]
And yes, there's a json blob that has everything necessary here.  I don't have the exact format right now, but it will say whether the answer was an arithmetic expression (and what the corresponding numbers are), a count, a span from the passage, or a span from the question.
