### ISSUE TITLE
SRL demo session breaks on a specific input sentence 

### ISSUE THREAD

**Issue by gabrielStanovsky** [allenai/allennlp-demo#186]
https://demo.allennlp.org/semantic-role-labeling/Njg2MzQ3

This then breaks on any other input until the session is refreshed.

**Comment by schmmd** [comment]
The issue here isn't that SRL is failing, but that when it does the entire experience breaks.

**Comment by jonborchardt** [comment]
i am unable to repro... since i cannot make it break, i cannot see how to keep the site looking good in a break
if you have repro, let me know
