### ISSUE TITLE
Skiff configuration uses 3x the resources

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-demo#194]
`kubectl get pods --namespace=allennlp-demo` shows 17 pods and we can store 4 pods on one machine.  Currently it's only staging with 1 replica, but eventually we also want a production with 2 replicas.  This would be 17 * 3 = 51 pods or 13 machines.

Previously we ran the AllenNLP demo on 5 n1-highmem-2 (the same machines that power skiff) so we can probably fit more pods on an individual node.

* [AllenNLP on Skiff](https://cloud.google.com/products/calculator/#id=146b2cef-ac1c-4d29-b985-85c8f0efc2cc)
* [AllenNLP pre-skiff](https://cloud.google.com/products/calculator/#id=fa88b86e-8abf-4a28-bda2-a10ff2323e13)

**Comment by schmmd** [comment]
@codeviking FYI

**Comment by codeviking** [comment]
Yikes! I talked to @joelgrus about this. My suspicion is that we can toggle the cpu and memory requested by each container and manage to use considerably fewer nodes.

@joelgrus Let me know if you need help tweaking those values.

**Comment by joelgrus** [comment]
I scaled everything down to 0.2cpu and 1Gi memory, I haven't looked to see which pods are doing ok with that and which are doing poorly
