### ISSUE TITLE
Use stackdriver-compatible logging

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-demo#196]
Now that the AllenNLP demo is on skiff our logs are streamed to Stackdriver.  Presently however the logging looks pretty bad, because Stackdriver doesn't know how to parse them.

![image](https://user-images.githubusercontent.com/954798/57546274-402f7100-7311-11e9-8827-80c4d9df3c75.png)

We should instead output our logs in JSON format in production.  This is how Sam handles this in the template:

https://github.com/allenai/skiff-template/blob/master/server/server/utils.py#L30
https://github.com/allenai/skiff-template/blob/master/server/server/start.py#L41

**Comment by joelgrus** [comment]
I think this is good now:

https://console.cloud.google.com/logs/viewer?interval=NO_LIMIT&project=ai2-reviz&authuser=1&minLogLevel=0&expandAll=false&timestamp=2019-05-13T20:59:56.389000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22container%22%0Aresource.labels.cluster_name%3D%22skiff-prod%22%0Aresource.labels.namespace_id%3D%22allennlp-demo%22%0Aresource.labels.project_id%3D%22ai2-reviz%22%0Aresource.labels.zone:%22us-west1-%22%0Aresource.labels.container_name%3D(%22allennlp-demo-reading-comprehension%22%20OR%20%22cloudsql-proxy%22)%0Aresource.labels.pod_id:%22allennlp-demo-staging-reading-comprehension-%22&scrollTimestamp=2019-05-13T20:52:33.006641177Z

**Comment by schmmd** [comment]
Looks good.  Let me check this out again near EOD when we have more history with the fix.
