### ISSUE TITLE
Create a /health route for AllenNLP

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-demo#197]
Currently we just use `/` for health checks and this traffic is hard to differentiate from real users hitting our site.  We should instead create a `/health` route that returns status code 200 and redirect health checks there.

https://github.com/allenai/allennlp-demo/blob/skiff/.skiff/webapp.jsonnet#L206

**Comment by joelgrus** [comment]
https://github.com/allenai/allennlp-demo/commit/963a402996b480f6c56379cf8952a2cd69e30c2c
