### ISSUE TITLE
Mangled sentence in hierplane

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-demo#20]
See the dependency parser with "He ate spaguetti with meatballs". http://staging.allennlp.org/dependency-parsing/MjU5Njg0

![image](https://user-images.githubusercontent.com/954798/44434413-d3e0c780-a55f-11e8-81a5-12c0286f4db5.png)

**Comment by DeNeutoy** [comment]
This was a problem with the parser. Although theoretically it can still happen, it is extremely unlikely.
