### ISSUE TITLE
Models should be hosted on GCS for speed and cost

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-demo#204]
Currently the demo downloads models from S3, which is slow.  Using a 750 MB model I did trials from a GCP machine using the following commands:

```
time wget https://s3.us-west-2.amazonaws.com/allennlp/models/bidaf-elmo-model-2018.11.30-charpad.tar.gz
time wget https://storage.cloud.google.com/allennlp-public-models/bidaf-elmo-model-2018.11.30-charpad.tar.gz
```

GCS averaged 3.1 s whereas S3 averaged 18.7.  I was glad to see this speedup even though I was pulling via https.

**Comment by schmmd** [comment]
@codeviking FYI (see the timing numbers above).

**Comment by codeviking** [comment]
Woah, that's wild.

For skiff, I wonder if we could just add a `model_files` parameter to `.skiff/config.json`.  During the cloud build process we could download those files to GCS, and somehow populate them in the container, etc.

**Comment by schmmd** [comment]
Done.
