### ISSUE TITLE
There's a weird shadow showing up over the left-hand side of AI2 banner.

### ISSUE THREAD

**Issue by codeviking** [allenai/allennlp-demo#227]
There's some sort of box-shadow in the top-left corner that's bleeding over the AI2 banner in the upper left corner:

![image](https://user-images.githubusercontent.com/801451/61260798-75eb3e80-a734-11e9-9295-7f715e988696.png)

This ends up just looking a little off, but isn't a big deal.

**Comment by jonborchardt** [comment]
I know what's up. I'll fix in the morning.

**Comment by jonborchardt** [comment]
fixed
