### ISSUE TITLE
The footer looks a little odd in the new treatment.

### ISSUE THREAD

**Issue by codeviking** [allenai/allennlp-demo#228]
On demos that are short (or prior to the demos being submitted), things look a little weird since the Footer has a dark background:

![image](https://user-images.githubusercontent.com/801451/61260854-ad59eb00-a734-11e9-86fc-a4ecf99f8821.png)

Could we either:

* Incorporate the footer into the pane system, so it shows up at the bottom, below both the left sidebar and the main content?
* Come up with a footer variant that uses a light background, so it's not noticeable?

Ping @Pelagic-sky for guidance.

**Comment by jonborchardt** [comment]
It cannot go under both panes. It needs to stay on the right.

**Comment by codeviking** [comment]
> It cannot go under both panes. It needs to stay on the right.

Why?

Using grid it should be possible to have a header at the top, pane on the left, and footer on thebottom -- no?

**Comment by jonborchardt** [comment]
Then the footer would be always visible.... And we don't want to sacrifice
that much Realestate.  Happy to discuss In person.

**Comment by codeviking** [comment]
Ah! That makes sense. Maybe we just consider an inverted version so it's less noticeable (i.e. one with a white background).

**Comment by Pelagic-sky** [comment]
Might want to come up with an alternate footer for applications/demos vs
marketing sites.

**Comment by jonborchardt** [comment]
options
1- push it way way down… super easy
2- remove it… super easy
3- make it grey… pretty easy
4- float it correctly at bottom… moderate

**Comment by Pelagic-sky** [comment]
![Screen Shot 2019-07-19 at 9 41 13 AM](https://user-images.githubusercontent.com/49924841/61551322-b0d9c480-aa09-11e9-9214-f1f74fd6888d.png)
Here's a good option for application/demo sites. It uses N2 as the background color and our default text and text link colors.

**Comment by schmmd** [comment]
The new color will be a significant improvement, but if you interact with the demo it's still going to have the odd behavior of jumping around quite a bit.  Try making some predictions and watching the footer.

**Comment by schmmd** [comment]
This is sufficiently addressed.
