### ISSUE TITLE
Warnings in docker

### ISSUE THREAD

**Issue by aolney** [allenai/allennlp-demo#233]
The current docker image is throwing a few warnings. Any suggestions on i) if these warnings should be ignored and ii) how to resolve these warnings if needed would be appreciated (I assume I would need to modify the docker image and commit the change):

1. DB Credentials

> {"message": "demo db credentials not provided, so not using demo db", "severity": "WARNING"}

2. min_padding_length

> /usr/local/lib/python3.6/site-packages/allennlp/data/token_indexers/token_characters_indexer.py:55: UserWarning: You are using the default value (0) of `min_padding_length`, which can cause some subtle bugs (more info see https://github.com/allenai/allennlp/issues/1954). Strongly recommend to set a value, usually the maximum size of the convolutional layer size when using CnnEncoder.

**Comment by schmmd** [comment]
@aolney you can ignore the first warning.  That just means that requests won't be logged into the database to create permalinks.

@joelgrus any ideas on the second?

**Comment by joelgrus** [comment]
I doubt the second is worth worrying about, my guess it's from a model that was trained before we added that feature.
