### ISSUE TITLE
Misaligned micro-header logo

### ISSUE THREAD

**Issue by aaronsarnat** [allenai/allennlp-demo#281]
![image](https://user-images.githubusercontent.com/8367927/68081616-1b9ee800-fdce-11e9-82be-13b6c0589614.png)

**Comment by aaronsarnat** [comment]
Assigning to @jonborchardt. FYI @Pelagic-sky.

**Comment by jonborchardt** [comment]
Yes, allennlp does not have up to date varnish.  Should be fixed.
