### ISSUE TITLE
AllenNLP content stretched across the entire horizontal space

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-demo#297]
For example, on a wide screen at https://demo.allennlp.org/open-information-extraction you have two VERY VERY wide input text boxes.  This looks bad (to me) and doesn't seem to follow general style guidelines.  It behaves exceptionally differently than the PRIOR demo, which aims to provide a similar overall experience.

![image](https://user-images.githubusercontent.com/954798/73485747-896c9880-4358-11ea-9d45-5baf9b565135.png)

To close this out, we should adjust the content so that it only fills a reasonable portion of the page.

**Comment by schmmd** [comment]
For a particular compelling example, look at https://demo.allennlp.org/user-models which looks terrible on a wide monitor.

**Comment by jonborchardt** [comment]
in review
