### ISSUE TITLE
Move to the PRIOR demo layout

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-demo#299]
The PRIOR demo has a slightly different layout than AllenNLP.  Presumably it was more carefully designed and we should move to that layout.

**Comment by schmmd** [comment]
@jonborchardt does this make sense?

**Comment by jonborchardt** [comment]
yes, however, layout and menu are still not officially supported by varnish.. so this should wait a bit

**Comment by jonborchardt** [comment]
i have done all we are planning to do here for the time being... let me know if there are other specifics we want form prior demo, and ill pull them over
