### ISSUE TITLE
Improve organization of the attention visualizations

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-demo#302]
The attention visualization effectively presents information in a visually compelling way, but the overall organization of portions of the model output over which to view the attention matrix is clunky and confusing.  For example, see https://demo.allennlp.org/atis-parser/MTM3MTcyNg==.

![image](https://user-images.githubusercontent.com/954798/73492195-11589f80-4365-11ea-984b-9d2cb8b6a5d3.png)

**Comment by matt-gardner** [comment]
I wouldn't say this has much to do with the attention visualization.  This has to do with a model that has multiple sequential outputs.

**Comment by schmmd** [comment]
Yes--the attention visualization itself seems fine.  Just the higher-level organization about how to get to it is a bit cumbersome.

**Comment by matt-gardner** [comment]
I don't know that we have (or can have) something better than that for this kind of output.  There's more than just attention that's shown for each output step, and the goal isn't to get to an "attention visualization", it's to see what the model was doing at each step.

**Comment by schmmd** [comment]
I think we could achieve something that's more aesthetic and self-explanatory, but I hear your point that EOD we still need a long list...

**Comment by matt-gardner** [comment]
I think my reaction is mostly to the issue title - it's not the attention visualization that you're complaining about here.

**Comment by schmmd** [comment]
Yep--it is poorly worded.

**Comment by jonborchardt** [comment]
@schmmd did you have a suggestion?
1- make accordion look nicer
2- add some text explaining what they are?
3- other?

**Comment by jonborchardt** [comment]
any better: 
![image](https://user-images.githubusercontent.com/8194065/83798985-f58a4080-a659-11ea-93bb-fb9267060735.png)
