### ISSUE TITLE
Sentiment Analysis output is boring

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-demo#304]
It simply writes the text "Positive" or "Negative" in a not-very-obvious way, with no notion of how certain the model is despite that information existing in the response.

```
{"label":"1","logits":[5.217404842376709,-5.244380474090576],"probs":[0.9999713897705078,2.8608292268472724e-05],"slug":"MTM3MTc0MA=="}
```

**Comment by jonborchardt** [comment]
in review
