### ISSUE TITLE
Tooltips are hidden by side nav

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-demo#314]
![image](https://user-images.githubusercontent.com/954798/74552975-33c4ee00-4f0b-11ea-8bef-b6ccd56768a6.png)

**Comment by matt-gardner** [comment]
My vote would be to change how this is displayed; we're going to have more reading comprehension models than it makes sense to have in a radio button, so we probably want a drop down select box, and then the tooltip text should be shown differently (perhaps just as a description underneath the select box).

**Comment by schmmd** [comment]
This is fixed by https://github.com/allenai/allennlp-demo/pull/316 (we're no longer using iframes).
