### ISSUE TITLE
coref model results differed from the demo

### ISSUE THREAD

**Issue by Moneyes1997** [allenai/allennlp-demo#317]
Demo: https://demo.allennlp.org/coreference-resolution/MTQ0MTI4MQ==

If I put sentences 'The woman reading a newspaper sat on the bench with her dog. It was eating bones.', the demo will return two coref groups, one for the woman and the other for the dog. However, using the model mentioned in the usage, I can have only the women cluster, and the one for dog is missing. I suspect it has something to do with the warning I got: 

UserWarning: You are using the default value (0) of `min_padding_length`, which can cause some subtle bugs (more info see https://github.com/allenai/allennlp/issues/1954). Strongly recommend to set a value, usually the maximum size of the convolutional layer size when using CnnEncoder

Do you know how to solve it?

PS: Here is what I got from the model in the usage:

{'top_spans': [[0, 4], [3, 4], [7, 8], [7, 11], [10, 10], [10, 11], [13, 13]],
 'predicted_antecedents': [-1, -1, -1, -1, 3, -1, -1],
 'document': ['The',
  'woman',
  'reading',
  'a',
  'newspaper',
  'sat',
  'on',
  'the',
  'bench',
  'with',
  'her',
  'dog',
  '.',
  'It',
  'was',
  'eating',
  'bones',
  '.'],
 'clusters': [[[0, 4], [10, 10]]]}

**Comment by ZhaofengWu** [comment]
The reason was that we updated the model in the coref but not the usage. You can substitute the model URL with `https://storage.googleapis.com/allennlp-public-models/coref-bert-lstm-2020.02.12.tar.gz` to get the same predictions. Note that we will make further updates to the model in the near future.

**Comment by Moneyes1997** [comment]
Thanks for the information! However, I still couldn't manage to load the model. Here is the error message:

ConfigurationError: 'pretrained_transformer_mismatched not in acceptable choices for model.text_field_embedder.token_embedders.tokens.type: [\'embedding\', \'character_encoding\', \'elmo_token_embedder\', \'elmo_token_embedder_multilang\', \'openai_transformer_embedder\', \'bert-pretrained\', \'language_model_token_embedder\', \'bidirectional_lm_token_embedder\', \'bag_of_word_counts\', \'pass_through\', \'pretrained_transformer\']. You should either use the --include-package flag to make sure the correct module is loaded, or use a fully qualified class name in your config file like {"model": "my_module.models.MyModel"} to have it imported automatically.'

Could you help me out?

**Comment by ZhaofengWu** [comment]
So the `coref-bert-lstm` model requires a more up-to-date version than `allennlp` v0.9.0 (but unfortunately is not compatible with master either). If you want to use a state-of-the-art coref model, I'd suggest watching for https://github.com/allenai/allennlp/pull/3848. Once it's merged (perhaps today or tomorrow), I will put a model link there, and you can then use that model after rebasing on the new master.

**Comment by lighteternal** [comment]
Hi @Moneyes1997 , it's probably a bit late but I just stumbled on this thread and since I was guided on how resolve the issue a while ago, you might want to read this: 
https://github.com/allenai/allennlp/issues/3792
