### ISSUE TITLE
Saliency Maps for the RoBERTa model in Sentiment Analysis Are not using WordPiece Tokenization

### ISSUE THREAD

**Issue by IsThatYou** [allenai/allennlp-demo#339]
The gradients returned by [interpret method](https://github.com/allenai/allennlp-demo/blob/master/app.py#L403) contains special tokens like [CLS] and [SEP]. Moreover, it splits words into subwords. However, in the current [code](https://github.com/allenai/allennlp-demo/blob/d4929b14422d0db17b192becab5235c6b0be6e97/demo/src/components/demos/SentimentAnalysis.js#L136), It splits words by space. This is definitely creating wrong/misaligned saliency maps. 

This may become a recurring issue going forward as more Transformer models are added. 

@ZhaofengWu

**Comment by matt-gardner** [comment]
Thanks for pointing this out @IsThatYou!  A PR to fix this is definitely welcome; we're a bit swamped with other things right now, so it'll take us a while to get to this.

**Comment by IsThatYou** [comment]
Currently, my temporary fix involves both changes in allennlp and allennlp-demo. Specifically, the dictionary returned by predict_json also contains the sentenced tokenized into wordpiece. Then I set `this.state.tokens =  json['tokens']`. This way on https://github.com/allenai/allennlp-demo/blob/d4929b14422d0db17b192becab5235c6b0be6e97/demo/src/components/demos/SentimentAnalysis.js#L136, we can comment out this line, and just use the tokens passed instead. Would this be helpful? I think one thing that I can think of to make this generalizable is to have the tokens displayed in interpretations to be returned from predict_json only. Instead of borrowing from requestData.

**Comment by matt-gardner** [comment]
Yes, if the predictor doesn't currently return the tokenized sentence, that's a problem, it needs to be added.  And then the UI should just use the tokenization returned by the predictor.  I agree with this solution.  Care to make whatever PRs are appropriate to fix this?

**Comment by IsThatYou** [comment]
Sure, I can do that. Should I also change the respective code in allennlp for sentiment analysis? Currently, I add the tokens in the `make_output_human_readable` method. This is kind of specific for each model type.

**Comment by matt-gardner** [comment]
Yeah, can you make a PR to allennlp also, to get the tokens passed through?  I'm not sure whether the best way is to do it in the model or the dataset reader, but we can figure that out once there's a PR.  Definitely start the PR with what you're doing now, and I'll look at it and see what we think.

**Comment by IsThatYou** [comment]
sounds good, I will @ you once I create a PR there.

**Comment by IsThatYou** [comment]
I should probably close this issue?

**Comment by matt-gardner** [comment]
Yep, thanks, closing now.
