### ISSUE TITLE
When hovering nested Coref highlight structure, only leaf should activate

### ISSUE THREAD

**Issue by aaronsarnat** [allenai/allennlp-demo#34]
Currently, when you hover over a highlight in a sub-tree of nested highlights, all nodes from root to the leaf get activated, but we only want to activate the leaf, as that is more relevant to the user, and thus a less-confusing experience.

**What we have now:**

![image](https://user-images.githubusercontent.com/8367927/44685118-8355e800-a9ff-11e8-895b-840822eb7568.png)

---

**What we want:**

![image](https://user-images.githubusercontent.com/8367927/44685125-88b33280-a9ff-11e8-955c-b1d392b989cd.png)

**Comment by aaronsarnat** [comment]
@schmmd please triage this issue on [Design Backlog](https://github.com/orgs/allenai/projects/7). Currently at the top.

**Comment by schmmd** [comment]
Closing as it's from 2018.
