### ISSUE TITLE
Design a new treatment for multiple models per task

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-demo#344]
The current option doesn't scale with more models.  Other aspects of the page are not designed to display information effectively per model either.  For example, our descriptions at the top of the page should only apply to the task and we should have an easily accessible description per model option.  Currently you can get a description on mouseover, but that's not obvious and cannot contain links to the publication.

Additionally, the usage treatment is per-task, but should really change per model.

**Comment by jonborchardt** [comment]
assigning this to @schmmd for text updates
https://github.com/allenai/allennlp-demo/pull/461
