### ISSUE TITLE
Colors do not fill the entire box sometimes

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-demo#35]
In the coreference example, sometimes the color squares do not fill the entire box.

![image](https://user-images.githubusercontent.com/954798/44687420-08dc9680-aa06-11e8-9925-ee0811e5085a.png)

http://demo.allennlp.org/coreference-resolution/Mjg4NjUw

**Comment by aaronsarnat** [comment]
Strange, I'm not seeing this... @schmmd can you tell me the following:

1) Which browser did you use to screenshot this?
2) Are you zoomed in or zoomed out? (CMD+0 will snap browser zoom to 100%, so if zooming changes, you'll know you weren't at 100%)

**Comment by schmmd** [comment]
Ah yes it is related to zoom. Try zooming in one level.  Since that's the cause I think this is pretty low priority.
