### ISSUE TITLE
Memory leak in the demo

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-demo#37]
The AllenNLP demo has a memory leak that causes pods to fail in Kubernetes.  Recently we added the dependency parser and pods were restarting every few minutes, so I doubled the memory available on each machine.  Regardless, I'm still seeing a few restarts overnight.

```
$ kubectl get pods
NAME                                     READY     STATUS    RESTARTS   AGE
allennlp-demo-prod-597b67546-mglpq       2/2       Running   3          18h
allennlp-demo-prod-597b67546-tfdnj       2/2       Running   2          18h
allennlp-demo-prod-597b67546-xzvjh       2/2       Running   4          18h
```

The user isn't seeing any impact because the pods restart when they crash and we have three replicas, but we are presently addressing the situation by spending more money (on replicas) and our ability to add more models is limited.

```
$ kubectl describe pod allennlp-demo-prod-597b67546-mglpq
Name:           allennlp-demo-prod-597b67546-mglpq
Namespace:      default
Node:           gke-allennlp-demo-cluster-new-pool-bdd08a8c-z0c5/10.9.254.14
Start Time:     Mon, 27 Aug 2018 13:46:54 -0700
Labels:         app=allennlp-demo-prod
                pod-template-hash=153623102
Annotations:    kubernetes.io/limit-ranger=LimitRanger plugin set: cpu request for container cloudsql-proxy
Status:         Running
IP:             10.4.14.10
Controlled By:  ReplicaSet/allennlp-demo-prod-597b67546
Containers:
  allennlp:
    Container ID:   docker://61c5625be2673d770391807f03e0060eb3948076a216fe75a8f1f616f048de2c
    Image:          allennlp/demo:e68ab81a7a52a1ee13831f90358f2698e9c90209
    Image ID:       docker-pullable://allennlp/demo@sha256:c16c141bba76bd4b73015ffb22739210e2ebc7c8427a70d22a60884579194761
    Port:           <none>
    State:          Running
      Started:      Tue, 28 Aug 2018 08:04:03 -0700
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Tue, 28 Aug 2018 05:06:44 -0700
      Finished:     Tue, 28 Aug 2018 08:04:02 -0700
    Ready:          True
    Restart Count:  3
    Limits:
      cpu:     1
      memory:  3000Mi
    Requests:
      cpu:      1
      memory:   3000Mi
    Readiness:  http-get http://:8000/ delay=15s timeout=1s period=3s #success=1 #failure=3
    Environment:
      ALLENNLP_DEBUG:          TRUE
      DEMO_POSTGRES_HOST:      127.0.0.1
      DEMO_POSTGRES_PORT:      5432
      DEMO_POSTGRES_DBNAME:    demo
      DEMO_POSTGRES_USER:      <set to the key 'username' in secret 'cloudsql-db-credentials'>  Optional: false
      DEMO_POSTGRES_PASSWORD:  <set to the key 'password' in secret 'cloudsql-db-credentials'>  Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-790xb (ro)
  cloudsql-proxy:
    Container ID:  docker://23cdfbe24b70f664d6b94ddd913f08649d165c1ff34efa2f767c3d4c7c559c68
    Image:         gcr.io/cloudsql-docker/gce-proxy:1.11
    Image ID:      docker-pullable://gcr.io/cloudsql-docker/gce-proxy@sha256:5c690349ad8041e8b21eaa63cb078cf13188568e0bfac3b5a914da3483079e2b
    Port:          <none>
    Command:
      /cloud_sql_proxy
      --dir=/cloudsql
      -instances=ai2-allennlp:us-central1:allennlp-demo-database=tcp:5432
      -credential_file=/secrets/cloudsql/credentials.json
    State:          Running
      Started:      Mon, 27 Aug 2018 13:47:35 -0700
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:        100m
    Environment:  <none>
    Mounts:
      /cloudsql from cloudsql (rw)
      /etc/ssl/certs from ssl-certs (rw)
      /secrets/cloudsql from cloudsql-instance-credentials (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-790xb (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          True 
  PodScheduled   True 
Volumes:
  cloudsql-instance-credentials:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  cloudsql-instance-credentials
    Optional:    false
  cloudsql:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
  ssl-certs:
    Type:  HostPath (bare host directory volume)
    Path:  /etc/ssl/certs
  default-token-790xb:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-790xb
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                  From                                                       Message
  ----     ------     ----                 ----                                                       -------
  Warning  Unhealthy  16m (x72 over 18h)   kubelet, gke-allennlp-demo-cluster-new-pool-bdd08a8c-z0c5  Readiness probe failed: Get http://10.4.14.10:8000/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  13m (x227 over 18h)  kubelet, gke-allennlp-demo-cluster-new-pool-bdd08a8c-z0c5  Readiness probe failed: Get http://10.4.14.10:8000/: dial tcp 10.4.14.10:8000: getsockopt: connection refused
```

I first noticed these issues around January 1, 2018.

**Comment by schmmd** [comment]
I just removed the memory limit from the Kubernetes configuration file (https://github.com/allenai/allennlp-internal/pull/54) which should alleviate some of the problem.  @ckarenz also mentioned that Kubernetes misreports memory usage which led their team to move away from memory limits.

**Comment by schmmd** [comment]
We still get reboots, but less frequently.

```
NAME                                     READY     STATUS    RESTARTS   AGE
allennlp-demo-prod-84f76c64c8-t8qr4      2/2       Running   2          2d
allennlp-demo-prod-84f76c64c8-v2jzx      2/2       Running   1          2d
allennlp-demo-prod-84f76c64c8-xq89k      2/2       Running   2          2d
allennlp-demo-staging-7df8ffc8d8-2nbbn   2/2       Running   0          2d
```

**Comment by ckarenz** [comment]
That indicates a legitimate leak, so memory limits are likely not your primary issue.

**Comment by schmmd** [comment]
Related: https://github.com/allenai/allennlp-demo/issues/82

**Comment by schmmd** [comment]
Another thing to note here is that this leak causes restarts, which clear our cache.  Additionally, I think the first time someone pings a model it's slowest.  So, in effect, our memory leak is causing our demo to feel quite slow for some of our users.

**Comment by somnathrakshit** [comment]
Any solution for the leak yet?

**Comment by schmmd** [comment]
@somnathrakshit unfortunately due to other priorities we have not looked into this yet.  But I'm curious--why do you ask?  Have you run into this as well @somnathrakshit?

**Comment by somnathrakshit** [comment]
Yes, I have been using the pretrained model for NER tagger. I am observing that the RAM usage increases continuously. For very long articles, the process even gets killed sometimes.

**Comment by schmmd** [comment]
@somnathrakshit are you using the pretrained model for the NER tagger inside a web demo?  Are you using the demo in this repository or the simple server in https://github.com/allenai/allennlp?

**Comment by somnathrakshit** [comment]
No, I am using my own code to get the named entities from text

**Comment by schmmd** [comment]
@somnathrakshit thanks for these details--they will help us narrow it down.  Do you run it over a large corpus in a loop and notice the RAM usage increased continuously as you process more and more documents?

**Comment by somnathrakshit** [comment]
Yeah, I am running it in a loop for a large corpus of documents and seeing the RAM usage increasing slowly.

**Comment by brendan-ai2** [comment]
Somewhat mysteriously there's not currently much evidence of a memory leak in the demo proper. Graphs of memory usage over time are mostly stable with occasional spikes since the last deploy. (Nearly a month now.) This could still be consistent with an OOM, of course, but it would be more likely the result of a query of death than a slow leak.

Looking at the current replica set backing the demo, `allennlp-demo-prod-894c8b57d`, it shows fairly new pods. These were apparently created when their backing VMs were restarted to handle an instance template update yesterday.

```
2019-01-24 15:39:26.679 PST
Compute Engine
setInstanceTemplate
us-central1-a:gke-allennlp-demo-default-pool-e8d3a1d3-grp
service-10554368204@container-engine-robot.iam.gserviceaccount.com
...
 2019-01-24 15:40:17.904 PST
Compute Engine
recreateInstances
us-central1-a:gke-allennlp-demo-default-pool-e8d3a1d3-grp
service-10554368204@container-engine-robot.iam.gserviceaccount.com
```

The only pod with a restart since then was due to a connection failure:
```requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))```

Full trace here: [allennlp-demo-prod-894c8b57d-8qdd4__restart_log.txt](https://github.com/allenai/allennlp-demo/files/2798289/allennlp-demo-prod-894c8b57d-8qdd4__restart_log.txt)

Actionable next steps (after AAAI):
1. Attempt to replicate the leak described by @somnathrakshit  by running NER against some corpus.
2. Dig into our logging/monitoring/metrics. Those may need to be augmented in order to really solve this issue. It doesn't appear that we're persisting very much either. The good news is https://app.google.stackdriver.com/?project=ai2-allennlp is fairly quiet. Mostly instance migrations with only one uptime failure in the last month.

There is the possibility that we were simply running a bit hot prior to @schmmd bumping the memory...

**Comment by brendan-ai2** [comment]
If I understand our logs correctly it appears that we log only after a query is completed. For instance, the logs containing a restart due to OOM:

```
E  10.36.2.1 - - [2019-02-05 18:47:54] "GET / HTTP/1.1" 200 16811 0.001380
 
E  02/05/2019 18:47:55 - INFO - server.db -   inserting into the database
 
E  02/05/2019 18:47:55 - INFO - server.db -   received perma_id 585879
 
E  02/05/2019 18:47:55 - INFO - __main__ -   prediction: {"model": "textual-entailment", "inputs": {"premise": "If you help the needy, God will reward you.", "hypothesis": "Giving money to the poor has good consequences."}, "cached": true, "outputs": {"label_probs": [0.8200667500495911, 0.03994963690638542, 0.13998357951641083]}, "slug": "NTg1ODc5"}
 
E  10.36.4.6 - - [2019-02-05 18:47:55] "POST /predict/textual-entailment HTTP/1.1" 200 5441 0.260685
 
E  10.36.4.6 - - [2019-02-05 18:47:55] "GET /assets/te-plot.svg HTTP/1.1" 200 929 0.001496
 
E  10.36.2.1 - - [2019-02-05 18:47:57] "GET / HTTP/1.1" 200 16811 0.001392
 
E  02/05/2019 18:47:58 - INFO - server.db -   inserting into the database
 
E  02/05/2019 18:47:58 - INFO - server.db -   received perma_id 585880
 
E  02/05/2019 18:47:58 - INFO - __main__ -   prediction: {"model": "dependency-parsing", "inputs": {"sentence": "Approximately how many items are in the V&A's textiles collection?"}, "cached": false, "outputs": {}, "slug": "NTg1ODgw"}
 
E  02/05/2019 18:49:19 - INFO - __main__ -   Starting a flask server on port 8000.
 
E  02/05/2019 18:49:19 - INFO - server.db -   Initializing demo database connection using environment variables
 
E  02/05/2019 18:49:19 - INFO - server.db -   initializing database connection:
 
E  02/05/2019 18:49:19 - INFO - server.db -   host: 127.0.0.1
 
E  02/05/2019 18:49:19 - INFO - server.db -   port: 5432
 
E  02/05/2019 18:49:19 - INFO - server.db -   dbname: demo
 
E  02/05/2019 18:49:19 - INFO - server.db -   successfully initialized database connection
 
E  02/05/2019 18:49:19 - INFO - __main__ -   loading machine-comprehension model
 
E  
  0%|          | 0/46175392 [00:00<?, ?B/s]
  0%|          | 89088/46175392 [00:00<00:51, 890815.01B/s]
 ```

**Comment by brendan-ai2** [comment]
And just to double check, I tried the last logged query "Approximately how many items are in the V&A's textiles collection?" and it the demo behaved normally, no crashing.

So the next logical steps are to finish improving the logging and monitoring. Importantly, we need to log before sending a query to a model.

**Comment by brendan-ai2** [comment]
@schmmd and I noticed an interesting failure mode today. One of the pods pegged its CPU and never recovered. (No corresponding memory pressure.) I have a PR out to address debugging what caused the failure in the first place, but we should also contemplate how to fix this robustly.

At a high level we'll need to set timeouts for handling requests. If we exceed them we need to kill either the container or the process performing the request. This should improve reliability by not leaving us with a reduced number of workers for an extended period.

**Comment by brendan-ai2** [comment]
Note: If you're using the Google's Cloud Shell to connect to the prod DB, be sure to run `export PGDATABASE=demo` before connecting. Otherwise you connect to a defunct (but superficially correct) DB.

**Comment by brendan-ai2** [comment]
I pushed the DB logging fix to prod successfully. Let's let that burn in over night and check for interesting queries in the morning!

**Comment by brendan-ai2** [comment]
I've manually correlated some container restarts with requests in the DB. Broadly speaking, they look like overly large queries. Naturally this can result in OOMs.

A basic approach to tackling this would be to query the DB for the longest successful request for each model and then use that to establish hard limits on request lengths. This is straightforward to implement.

Recent errors: [failures.txt](https://github.com/allenai/allennlp-demo/files/2882503/failures.txt)

**Comment by schmmd** [comment]
Yuck!  Yeah, it particularly makes sense to filter our "sentence input" models.  I'm a bit embarrassed I didn't do this earlier!

I'd make it some % shorter than the longest successful request (maybe half that length?)  Even if those queries succeed--they might have quite a bit of drag on the demo!

**Comment by brendan-ai2** [comment]
Fix deployed. I'll keep an eye on it over the next few days to see if stability improves.

**Comment by schmmd** [comment]
Resolved by @brendan-ai2.
