### ISSUE TITLE
Disable ability to run model until required input fields are not empty

### ISSUE THREAD

**Issue by aaronsarnat** [allenai/allennlp-demo#40]
This applies to:

- enabled/disabled state of submit button
- handling of "Enter" `keyDown` event.

---

**Ideally we would see this until all required fields are filled in:**

![image](https://user-images.githubusercontent.com/8367927/44749736-46095d00-aac8-11e8-9684-a6d5e6e64869.png)

---

**This would help us avoid this experience:**

![image](https://user-images.githubusercontent.com/8367927/44749774-66d1b280-aac8-11e8-9a92-1eecd621d981.png)

**Comment by schmmd** [comment]
This was done a long time ago.
