### ISSUE TITLE
Make Wikitables Parser demo look nicer

### ISSUE THREAD

**Issue by aaronsarnat** [allenai/allennlp-demo#42]
This issue is related to the PR: [Adding (hidden) demo for wikitables parser (#25)](https://github.com/allenai/allennlp-demo/pull/25).

---

**Comment by matt-gardner** [comment]
Note that this demo can now be viewed here: http://staging.allennlp.org/wikitables-parser.

**Comment by aaronsarnat** [comment]
Closing, as this is issue is redundant.

---

This task was partially addressed when the following PR was merged:

- [`allennlp-demo:` Adding general `<SyntaxHighlight />` component and implementing it in WikiTables demo (#77)](https://github.com/allenai/allennlp-demo/pull/77)

The remaining sub-tasks related to WikiTables demo UX are being tracked in the following issues:

- [`allennlp-demo:` Update the Attention Visualization (#44)](https://github.com/allenai/allennlp-demo/issues/44)
- [`allennlp-demo:` Improve table input UX for semantic parsing (#64)](https://github.com/allenai/allennlp-demo/issues/64)
- [`allennlp:` Add whitespace formatting to WikiTables logical form output (#1828)](https://github.com/allenai/allennlp/issues/1828)
