### ISSUE TITLE
NAQANET blows up the demo

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-demo#482]
When I try to predict anything with NAQANET I get a blank page.  Here's the console output.

![image](https://user-images.githubusercontent.com/954798/84521581-13732900-ac8a-11ea-8abe-411473ec9b63.png)

/predict seems to return results however.

![image](https://user-images.githubusercontent.com/954798/84521641-2d147080-ac8a-11ea-8598-630e70039a91.png)

**Comment by aimichal** [comment]
Hint: the local version of the UI showed some diagnostics that pointed to the problem being in the Collapse component:

```
The above error occurred in the <Collapse> component:
    in Collapse (created by Collapse)
    in Collapse (at ReadingComprehension.js:251)
```

So I replaced it with a `<div>` like this:

```diff
diff --git a/ui/src/components/demos/ReadingComprehension.js b/ui/src/components/demos/ReadingComprehension.js
index 83fad84..eeef8d5 100644
--- a/ui/src/components/demos/ReadingComprehension.js
+++ b/ui/src/components/demos/ReadingComprehension.js
@@ -248,12 +248,12 @@ const Attacks = ({attackData, attackModel, requestData}) => {
 
   return (
     <OutputField label="Model Attacks">
-      <Collapse>
+      <div>
         {inputReduction}
         <HotflipPanel>
           <HotflipComponent hotflipData={hotflipData} hotflipFunction={attackModel(requestData, HOTFLIP_ATTACKER, NAME_OF_INPUT_TO_ATTACK, NAME_OF_GRAD_INPUT)} />
         </HotflipPanel>
-      </Collapse>
+      </div>
     </OutputField>
   )
 }
```

And now there's no more crash. Probably not the right fix, but maybe it's a clue where to start looking!

I also notice that responses are weird. Clicking "Run" in succession on the same inputs alternatively gives different answers. Looks like successive responses from the server are different. That is, given the following `curl ... | jq` invocation:

```
curl -s 'https://demo.allennlp.org/api/naqanet/predict' -H 'Content-Type: application/json' --data-raw '{"model":"naqanet","passage":"Kerbal Space Program (KSP) is a space flight simulation video game developed and published by Squad for Microsoft Windows, OS X, Linux, PlayStation 4, Xbox One, with a Wii U version that was supposed to be released at a later date. The developers have stated that the gaming landscape has changed since that announcement and more details will be released soon. In the game, players direct a nascent space program, staffed and crewed by humanoid aliens known as \"Kerbals\". The game features a realistic orbital physics engine, allowing for various real-life orbital maneuvers such as Hohmann transfer orbits and bi-elliptic transfer orbits.","question":"What does the physics engine allow for?"}' | jq .answer.value
```

The result is either `"real-life orbital maneuvers"` or `"game, players direct a nascent space program...`. So that's something else to look into!

**Comment by schmmd** [comment]
@matt-gardner would you expect NAQANET to return nondeterministic results?

**Comment by matt-gardner** [comment]
That's the wrong model result. There shouldn't be a `program_lisp` for NAQANET.  Did something get hooked up wrong?

**Comment by aimichal** [comment]
I've peeled off the question of non-determinism to another issue: https://github.com/allenai/allennlp-demo/issues/485 -- sorry for mixing things up here.

Let's focus on the UI problem in this issue.

@schmmd I don't see a "program_lisp" in responses from NAQANet, but I do see a runtime crash in the browser that is remedied by the `<div>` thing I mentioned. Going to dig into this a bit more now.
