### ISSUE TITLE
NMN always returns "No results" despite results in /predict

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-demo#483]
![image](https://user-images.githubusercontent.com/954798/84521752-52a17a00-ac8a-11ea-9365-aa4c987de3c6.png)

![image](https://user-images.githubusercontent.com/954798/84521740-4f0df300-ac8a-11ea-8996-50f8eba252ae.png)

**Comment by aimichal** [comment]
Okay, I can repro in prod by going to https://demo.allennlp.org/reading-comprehension/, choosing the model NMN and the example "Who stars in The Matrix?". The server responds with an answer, but "No answer returned" is shown.

**Comment by aimichal** [comment]
Same thing locally. Debugging now!
