### ISSUE TITLE
Create a social sharing card for AllenNLP

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-demo#488]
I know next to nothing about social sharing cards, but this content looks appropriate.  Since I've never done this before, I'd like @jonborchardt to put this up when he's back on Monday.  @carissas is putting together an image.

```
<meta property="og:url" content="http://demo.allennlp.org/" />
<meta property="og:type" content="website" />
<meta property="og:image" content="FIXME" /> 
<meta property="og:title" content="AllenNLP Demo" /> 
<meta property="og:description" content="A collection of interactive demos of over 20 popular NLP models" />
```

**Comment by schmmd** [comment]
![image](https://user-images.githubusercontent.com/954798/84552653-89958100-acc6-11ea-9eca-a0d2fca7258d.png)

**Comment by schmmd** [comment]
See https://github.com/allenai/allennlp-demo/issues/491 for the image.

**Comment by jonborchardt** [comment]
done
