### ISSUE TITLE
Support hosting multiple models for the same task

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-demo#49]
**Motivation:** we have multiple models for many of our tasks, but the demo design supports only one model per task.  Researchers would like compare different approaches on the same task interactively through our demo.

**Success Criteria:** we a clean design for multiple models per task that can scale to many (3x) more models than we have today.  We also implement multiple models for at least two tasks.  It should also be easy (e.g. just a configuration change) to add an additional model for an existing task.

**Comment by schmmd** [comment]
This is a broad project that may overlap with some of our others (such as Docker-to-Demo) so we're sidelining this for the time being.  It also would be helpful to have a designer on staff as it's a more radical change to the whole demo.

**Comment by matt-gardner** [comment]
I'm ok closing this or keeping it open - we have an interim solution that works for two models, but we do need some design work for when we have more than a few model options.

**Comment by OyvindTafjord** [comment]
Ignore my close/open action, just confused button clicking while browsing a task board...

**Comment by matt-gardner** [comment]
No worries; I commented because there is actually an update here, because of recent work on getting multiple models into the demo.

**Comment by schmmd** [comment]
Whew!  I'm going to close this since it we have a solution for the base problem and we have a few confusing comments on this thread (particularly the one from me!)  It'd be good to have a separate issue that clearly highlights the problem we'll have when we have many models (I think it's just that the list will become unwieldy.
