### ISSUE TITLE
Entity Detection Quality Issue between Pre-trained Model output vs Allen Demo Page output

### ISSUE THREAD

**Issue by vijayatgithub** [allenai/allennlp-demo#495]
Hi Team,

We have been using NER system for one of our business use case for years. Recently we have planned to replace "Standford - NER" library with "Allen NLP NER" after reviewing several name detection patterns using demo page link [https://demo.allennlp.org/named-entity-recognition] and we moved to towards developing an entity detection bot on the top of Allen NLP - NER model.

So we have download the model "fine-grained-ner-model-elmo-2018.12.21.tar" from the web and developed a script to consume the model.

After bot development, we have tested few samples with it, but the results came out from the model was completely wrong. The model should identify Person names, Organization from the input string but it is not working when the content is mixed with entities and plain words. I have attached the samples which I have tested for your review. Please look into this and help us to overcome this issue.

[Test 1.txt](https://github.com/allenai/allennlp-demo/files/4786798/Test.1.txt)
[Test 2.txt](https://github.com/allenai/allennlp-demo/files/4786795/Test.2.txt)
[Test 3.txt](https://github.com/allenai/allennlp-demo/files/4786796/Test.3.txt)
[Test 4.txt](https://github.com/allenai/allennlp-demo/files/4786823/Test.4.txt)

Note:
All 4 Test inputs returned expected results in Demo page.

Test Input 4:

![image](https://user-images.githubusercontent.com/11333298/84779936-9d145500-b002-11ea-849c-31d5b5a17337.png)

Test Input 1:

![image](https://user-images.githubusercontent.com/11333298/84779680-51fa4200-b002-11ea-8189-fbcbbde305a7.png)

**Comment by schmmd** [comment]
This model uses ELMo and needs a warm up if you're running it offline.  We have a number of issues closed on the allennlp repo that cover this same problem.

This behavior is confusing, and we're planning on replacing our ELMo models with BERT models to avoid confusion in the future.

**Comment by schmmd** [comment]
Here's the relevant documentation: https://github.com/allenai/allennlp/blob/v0.9.0/tutorials/how_to/elmo.md#notes-on-statefulness-and-non-determinism
