### ISSUE TITLE
How the 'hotflip' is implemented in in the demo?

### ISSUE THREAD

**Issue by JJumSSu** [allenai/allennlp-demo#522]
Hi, this [hotflip](https://demo.allennlp.org/masked-lm?text=The%20doctor%20ran%20to%20the%20emergency%20room%20to%20see%20%5BMASK%5D%20patient.) demo is so cool.

However, I have a question. BERT uses wordpiece vocabulary and is subword-unit based language model. But in the demo, it seems that the token is flipped at the "word" level. Also, the hotflip attack implementation in the allennlp [library](https://github.com/allenai/allennlp/blob/master/allennlp/interpret/attackers/hotflip.py) is based on word-level. 

Did you guys give special treatment for this discrepancy? Or do you guys just flip the token at the subword-level?
I couldn't find out the source code processing this part.

Thank you.

**Comment by matt-gardner** [comment]
Closing this in favor of the [identical issue](https://github.com/allenai/allennlp/issues/4516) on the main allennlp repo.
