### ISSUE TITLE
Implement standardized attribution format for all models in the demo

### ISSUE THREAD

**Issue by aaronsarnat** [allenai/allennlp-demo#53]
This issue is based on [this comment](https://github.com/allenai/allennlp-website/issues/72#issuecomment-420691285) by @matt-gardner.

---

demo.allennlp.org should have a standard format for displaying this information.  Something like

```
Original paper: [title and venue]
Original authors: [list, with affiliation]
This version implemented by: [list, with affiliation]
Description:
```

It'll make it more obvious who should get credit for what when someone is looking at the demo.

**Comment by schmmd** [comment]
Closing as it's from 2018.
