### ISSUE TITLE
Wrong model for RoBERTa MNLI?

### ISSUE THREAD

**Issue by ZhaofengWu** [allenai/allennlp-demo#596]
The MNLI page references the SNLI model. Not sure what this new field is for, but is this intended?

https://github.com/allenai/allennlp-demo/blob/f03823d90468b84803a64a87a9cecdac05309838/api/allennlp_demo/roberta_mnli/model.json#L3

**Comment by ZhaofengWu** [comment]
The usage tab of the MNLI model also has the evaluation instruction on the *SNLI* test set:
```
allennlp evaluate \
    https://storage.googleapis.com/allennlp-public-models/mnli_roberta-2020.06.09.tar.gz \
    https://s3-us-west-2.amazonaws.com/allennlp/datasets/snli/snli_1.0_test.jsonl
```
Either this is a consequence of this incorrect pretrained_model_id, or it's another independent error?

**Comment by dirkgr** [comment]
This looks wrong. I made the fix.
