### ISSUE TITLE
Interpret requests for the ELMo-BiDAF Model Fail.

### ISSUE THREAD

**Issue by codeviking** [allenai/allennlp-demo#675]
### Task
Reading Comprehension

### Model
ELMo-BiDAF

### Feature
Interpret Requests

### Issue
The interpret requests often timeout. The UI displays the loading indicator indefinitely, but inspecting things more closely reveals that the response is a 504 (gateway timeout).

I can refresh the page and sometimes get a snappy response by resubmitting the same request. This is probably the cache kicking in.

This probably isn't a bug in the backend, but rather a case where we need to expand the timeout that's set in NGINX (unfortunately I think there might be multiple timeouts, as there are probably several layers of reverse proxies to fiddle with).

The default timeout is 60s, if someone call tell ReViz a more appropriate upper bound we can work that in.

**Comment by schmmd** [comment]
We need to remove this for now, as it's too slow to provide a compelling experience.  I think Jon has done this.

**Comment by jonborchardt** [comment]
i have removed the control from the ui via config
