### ISSUE TITLE
The BiDAF HotFlip Attack doesn't return a new Prediction

### ISSUE THREAD

**Issue by codeviking** [allenai/allennlp-demo#683]
### Task
Reading Comprehension

### Model
BiDAF

### Feature
HotFlip Attack

### Issue

The HotFlip attack output has space for an updated prediction, but nothing is displayed there:

![Screen Shot 2020-12-23 at 2 04 45 PM](https://user-images.githubusercontent.com/801451/103040289-d1278000-4527-11eb-9d59-e4c9e4bb9155.png)

I looked at the response and there's nothing in the response that looks like an updated prediction. So either this information doesn't exist or it's being lost somewhere.

**Comment by dirkgr** [comment]
Is this the same issue @jonborchardt and I were talking about yesterday? I believe the hot flip attack returns nothing but the new prediction.

**Comment by jonborchardt** [comment]
fixed
