### ISSUE TITLE
Infrastructure Tracking

### ISSUE THREAD

**Issue by brendan-ai2** [allenai/allennlp-demo#69]
Later this year we anticipate investing in our demo infrastructure. Our goals are to 1) add the ability to easily host external models and 2) improve robustness (in engineering sense).

Motivation: We’d like to add many more models to the demo, but the present architecture isn’t scalable as everything runs in a single process on a single thread.  In addition, we would like to be able to add demos for contributed models that are not merged into AllenNLP.

Success criteria: we close out the following issues:
"Memory leak in the demo" - https://github.com/allenai/allennlp-demo/issues/37
"Add the ability to host external models in the demo" - https://github.com/allenai/allennlp-demo/issues/38
"Support hosting multiple models for the same task" - https://github.com/allenai/allennlp-demo/issues/49

We'll flesh this issue out as we refine our plan.

**Comment by schmmd** [comment]
We've done all three by now ;-)
