### ISSUE TITLE
Fix bugs in Event2Mind demo.

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-demo#70]
Currently the demo has some glaring bugs.  We want to fix this so that it's somewhat usable--even though it won't be fully usable until we improve the design.

- [x] Currently the input text is lost when something is submitted.
- [x] On the right, the user can select between "Tree" and "Text" but that option does nothing.

**Comment by aaronsarnat** [comment]
I can fix these

**Comment by aaronsarnat** [comment]
@schmmd FYI there's a PR for fixing this: https://github.com/allenai/allennlp-demo/pull/71
