### ISSUE TITLE
changing models in tugboat components crashes the app

### ISSUE THREAD

**Issue by jonborchardt** [allenai/allennlp-demo#717]
got to /hidden/reading-comprehension
run a model, say nmn, first example

then after the result appears, simply select a new model, say naqanet

result: crash
![image](https://user-images.githubusercontent.com/8194065/104631399-0cadf980-5651-11eb-9468-899a5c865784.png)

expected: answer clears out and no crash

**Comment by codeviking** [comment]
Fixed in #722.

**Comment by codeviking** [comment]
This should be resolved.
