### ISSUE TITLE
Refactor demo front-end

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp-demo#72]
**Motivation**

Right now the front-end code for our demo is sort of a mess. All of the `Component`s for each model/task contain a ton of duplicated code and lots of bespoke UX components.

This means that right now to add a new model to the demo takes hundreds of lines of JavaScript. By factoring out common code (and cleaning it up), we should be able to make it so that a new model takes only a few dozen lines of JavaScript. This will make it much simpler to add new models and avoid subtle UI bugs as we grow the demo.

As part of this process, we should add unit tests and (potentially) TypeScript/Flow type annotations to make our demo harder to break and easier to keep running.

**Success Criteria**

* A clean set of reusable React components that can be used to quickly create new demo components.
* Good unit test coverage for our demo FE
* Type hinting and checking for our demo FE
* CI that verifies these

**Comment by schmmd** [comment]
@matt-gardner says a student at UCI used the new NER visualization for a new demo and found it super helpful.

**Comment by schmmd** [comment]
Fixed in https://github.com/allenai/allennlp-demo/pull/117
