### ISSUE TITLE
Attention module is not working in AllenNLP Demo

### ISSUE THREAD

**Issue by YisongMiao** [allenai/allennlp-demo#731]
Hi NLPers at AllenAI:

Greetings from Yisong, an NLPer at NUS.

I just found that one module is down on the AllenNLP website. 

In the Text Entailment section (https://demo.allennlp.org/textual-entailment), I tried to plot the attention of premise to hypothesis, the website told me something is wrong and couldn't display.
I did similar things months before, it was working then. Could you help me solve this issue?

Many thanks!
Yisong

**Comment by schmmd** [comment]
@YisongMiao sorry you ran into this problem!  What do you plan to use the attention visualization for?  We are actually in the process of removing this from our demos, which may be why something broke recently.  You might have the best luck running the demo locally from a commit that happened a while ago (September 1st?) to get the attention information you're looking for.

@dirkgr do you have any other ideas / insight?

**Comment by dirkgr** [comment]
I tried it just now and it worked fine. @YisongMiao, what was the example you gave it? Maybe it has something to do with that?

**Comment by YisongMiao** [comment]
Dear NLPers at Allen:

Thanks for being so responsive!

Well, it seems like still not working, 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/11874006/105937785-34f61900-6091-11eb-81ae-dd49954f0271.png">

Well, I want to have many online tries (e.g. changing some words and see their attention change), so it's better that I can have a web interface.

Thanks again, I appreciate your efforts.

Cheers,
Yisong

**Comment by schmmd** [comment]
@YisongMiao my point was that you may could run the web interface locally...

**Comment by schmmd** [comment]
@YisongMiao we're going to remove this visualization entirely from the AllenNLP demo in the next couple of days, so we won't fix the issue there.  However, you can quite easily run a copy of the AllenNLP demo locally.  I got the attention visualization to work in this way by doing the following:

```
$ git checkout d597d7ae894df8a4d3155c01bbbfac07f613f01e
$ MODEL=elmo_snli docker-compose up --build
```

It takes a few minutes for the model to load (you can view progress with `docker-compose logs model`), but once it's up you can navigate to http://localhost:8080 and run the textual entailment demo.

![image](https://user-images.githubusercontent.com/954798/106033364-88169e80-6086-11eb-964e-ea35d6ea85ab.png)

**Comment by YisongMiao** [comment]
@schmmd Hi Michael, thanks for your note, I will try then!

Cheer,
Yisong
