### ISSUE TITLE
Wrapping changes when dropdowns are opened

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-demo#771]
When a dropdown is opened, the horizontal wrapping is affected.  Consider https://demo.allennlp.org/coreference-resolution/coreference-resolution/s/we-are-looking-for-them/K8G8P7Q8N7.  When the CLI output is closed, the output wraps correctly.

![image](https://user-images.githubusercontent.com/954798/105880726-8d0d1c80-5fb8-11eb-8a7a-75ef4018e278.png)

However when it is opened, the wrapping changes.

![image](https://user-images.githubusercontent.com/954798/105880768-97c7b180-5fb8-11eb-9e27-0c152076b9ee.png)

**Comment by jonborchardt** [comment]
fixed
