### ISSUE TITLE
Effectively demos at least 4 semantic parser visualizations

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-demo#78]
Not only do we want to improve our demo visualizations (e.g. https://github.com/allenai/allennlp-demo/issues/76 and https://github.com/allenai/allennlp-demo/issues/64) but we would like to add more semantic parser visualizations to complete the semantic parsing toolkit.  Doing this will probably involve reworking the left pane so we can group the Semantic Parsing demos together--otherwise the list starts to become unmanageable.

**Comment by schmmd** [comment]
@matt-gardner can you list the semantic parsers we want to visualize--and the contact for each?

**Comment by matt-gardner** [comment]
1. WikiTableQuestions (contact: @matt-gardner)
2. Cornell Natural Language Visual Reasoning (NLVR) (contact: @pdasigi)
3. ATIS (contact: @kl2806)
4. QuaRel (contact: @OyvindTafjord)

**Comment by schmmd** [comment]
Closing as we have the four Semantic Parser models in the demo but we have some "hangover" work around the visualizations that Aaron wasn't able to quite get to.  Visualization work captured in https://github.com/allenai/allennlp-demo/issues/130.
