### ISSUE TITLE
URLs don't work with a trailing slash

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-demo#79]
For example, http://demo.allennlp.org/event2mind works fine but http://demo.allennlp.org/event2mind/ 404's.  I frequently share URLs in the latter format because I copy and paste a permalinked URL and then manually remove the suffix.  Ideally either format would work.

**Comment by schmmd** [comment]
This seems to be due to something in the Kubernetes ingress routing.  The requests fail before even making it to React.  The behavior works locally.

From the nginx request logs:

```
{"time": "2019-07-29T18:28:48+00:00", "proxy_upstream_name": "allennlp-demo-allennlp-demo-staging-8000", "proxy_upstream_addr": "10.50.150.39:8000", "request_method": "GET", "request_uri": "ht
tps://demo.staging.allennlp.org/reading-comprehension/", "status": 404, "upstream_status": 404, "request_length": 40, "body_bytes_sent": 232, "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac O
S X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36", "remote_addr": "66.165.20.89", "realip_remote_addr": "66.165.20.89", "referer": "", "upstream_response_
time": 0.003, "upstream_connect_time": 0.000, "upstream_header_time": 0.003, "request_time": 0.002, "host": "demo.staging.allennlp.org", "ssl_protocol": "TLSv1.2", "scheme": "https" }
```

Here's where the route is added for the base application.  I tried removing the `path` part, but it still didn't work.

https://github.com/allenai/allennlp-demo/blob/master/.skiff/webapp.jsonnet#L202

**Comment by schmmd** [comment]
We now think the issue is in the python component, which makes sense since this issue predates the k8s config.

**Comment by schmmd** [comment]
Fixed

**Comment by anentropic** [comment]
neither with or without the slash seems to work any more

**Comment by anentropic** [comment]
same for https://demo.allennlp.org/quarel-parser-zero/

(I had a few of these model demos bookmarked and these two seem to be gone)

**Comment by schmmd** [comment]
@anentropic yes they've both been removed.  For Event2Mind, I highly recommend looking at https://mosaickg.apps.allenai.org/ which features extensions of the original Event2Mind model.

**Comment by anentropic** [comment]
thanks, those demos are impressive!
