### ISSUE TITLE
Better integrate the demo with the main site

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-demo#81]
Currently we have duplicated data on [the Models page](https://allennlp.org/models) and in the AllenNLP demo.  For example, both maintain a list of models and descriptions for each of those models.

We should have a closer integration so we duplicate less and "rebrand" beyond "demo". 
 "Interactive AllenNLP" is more than a demo--it's AllenNLP in action.

Specifically I would like to move the model information from https://allennlp.org/models into https://allennlp.org/demo.  We would then rebrand the page to just contain our gallery of contributed models.

- [ ] Move code examples for predictions, evaluations, and retraining to the demo.
- [ ] Remove the "Our Models" section from https://allennlp.org/models.
- [ ] Rename https://allennlp.org/models to https://allennlp.org/gallery and focus only on our user gallery.

**Comment by aaronsarnat** [comment]
"Explore Models" ?

**Comment by schmmd** [comment]
Some thoughts from Oren:

I wonder if we should update the wording on the allenNLP home page from “view demo” because:

It’s plural: demoS.
It’s beyond showing some kind of demo fhte library—it’s a large variety of models ‘in action’…  Perhaps we should have explicit links/images to the different model on the home page.
 

Compare with the lay out at the top of this page: https://prior.allenai.org/research
