### ISSUE TITLE
Model usage tab doesn't fully update when switching models

### ISSUE THREAD

**Issue by dirkgr** [allenai/allennlp-demo#827]
When I click around the Reading Comprehensions models I see this problem. I'm in the Model Usage tab and I change models. Everything updates, except for the things under the heading "Predictions". When I leave the tab and come back, it's updated.

I use Safari.

**Comment by dirkgr** [comment]
Update: When I select the text that didn't update, it updates. I now see two copies of the text above each other.
<img width="1111" alt="Screen Shot 2021-02-10 at 15 14 33" src="https://user-images.githubusercontent.com/920638/107585234-b29e4680-6bb2-11eb-8ec3-6e9a3faa6137.png">

**Comment by codeviking** [comment]
@dirkgr This appears to be fixed in production. Let me know if it's not fixed for you!

**Comment by dirkgr** [comment]
Looks good!
