### ISSUE TITLE
Refactor <Pane />

### ISSUE THREAD

**Issue by aaronsarnat** [allenai/allennlp-demo#88]
There are structural issues with the current `<Pane />` system that are causing annoying scrolling bugs. A refactor is necessary for:

1. Preparing for a Q4 demo app refactor
2. Prerequisite for [Replace nested Accordion UX with Drawer system (#89)](https://github.com/allenai/allennlp-demo/issues/89)

---

- Use [panda](https://github.com/allenai/euclid/tree/master/panda/web/src) as example
- Make sure it works with hierplane (at least as well as current implementation)
- make nav menu pane more robust

**Comment by schmmd** [comment]
Closing as it's from 2018.
