### ISSUE TITLE
The UI integration tests aren't working right.

### ISSUE THREAD

**Issue by codeviking** [allenai/allennlp-demo#903]
See [this run](https://github.com/allenai/allennlp-demo/pull/896/checks?check_run_id=2195484227).

It failed in CI, but works locally. We should investigate and figure out why it's not consistent.

**Comment by jonborchardt** [comment]
these appear to be working...
i have run this a bunch of times... all green:
https://github.com/allenai/allennlp-demo/pull/912/checks?check_run_id=2222843810
