### ISSUE TITLE
Make HeatMap table headings "sticky" on scroll

### ISSUE THREAD

**Issue by aaronsarnat** [allenai/allennlp-demo#94]
![attention-sticky](https://user-images.githubusercontent.com/8367927/46628753-814d7180-caf3-11e8-9a7f-dac0aa3c2f4d.gif)

---

Since the attention visualization HeatMap tables often have many rows, we want to visually retain context when users scroll. Sticky table headers are the most straightforward solution:

---

**Essential**
- Column labels

---

**Nice to have**
- Row labels

**Comment by aaronsarnat** [comment]
This task is based on the recent aspirational design for the new Attention Visualization:

[![image](https://user-images.githubusercontent.com/8367927/46327384-3d6be100-c5b6-11e8-8b7b-d50ce3ee2145.png)](https://drive.google.com/file/d/1WoCAjcUfT0SvZY2aNJuhoFeXGgnvo8ZR/view?usp=sharing)

**Comment by jonborchardt** [comment]
With the new redesign, adding sticky headers is not possible.  if we decide we need this, we would ned to constrain the height of the heatmap space which would be a large change as seen in the video.  Closing for now.
