### ISSUE TITLE
Add angled column labels to HeatMap

### ISSUE THREAD

**Issue by aaronsarnat** [allenai/allennlp-demo#95]
![image](https://user-images.githubusercontent.com/8367927/46628501-9d044800-caf2-11e8-803d-4597f65016f1.png)

---

This will make the column labels easier to read.

**Comment by aaronsarnat** [comment]
This task is based on the recent aspirational design for the new Attention Visualization:

[![image](https://user-images.githubusercontent.com/8367927/46327384-3d6be100-c5b6-11e8-8b7b-d50ce3ee2145.png)](https://drive.google.com/file/d/1WoCAjcUfT0SvZY2aNJuhoFeXGgnvo8ZR/view?usp=sharing)

**Comment by schmmd** [comment]
Closing as it's from 2018.
