### ISSUE TITLE
Add custom tooltip for displaying HeatMap cell values

### ISSUE THREAD

**Issue by aaronsarnat** [allenai/allennlp-demo#97]
![image](https://user-images.githubusercontent.com/8367927/46628319-09327c00-caf2-11e8-9b92-8f8aac11d4cd.png)

- Same look and feel as `<Highlight />` tooltip (e.g. NER)
- Instantly shown on hover (no need to wait several seconds for browser tooltip to show up)
- Could support additional metadata beyond cell value (TBD)

---

Note:

- For initial release, we don't want to show normalization type in the tooltip. Only the value.
- May want to round floating points to nearest hundredth or thousandth (TBD)
- [Crosshair UI](https://github.com/allenai/allennlp-demo/issues/96) is being tracked in a separate issue

**Comment by aaronsarnat** [comment]
This task is based on the recent aspirational design for the new Attention Visualization:

[![image](https://user-images.githubusercontent.com/8367927/46327384-3d6be100-c5b6-11e8-8b7b-d50ce3ee2145.png)](https://drive.google.com/file/d/1WoCAjcUfT0SvZY2aNJuhoFeXGgnvo8ZR/view?usp=sharing)

**Comment by aaronsarnat** [comment]
@matt-gardner @schmmd Note that despite the mockup, I'm not going to add the normalization type to the tooltip (as discussed on a separate thread with Matt).

However, I wanted to ask about rounding of floating point numbers. Michael called out the possibility of rounding to the nearest hundredth (or thousandth?). I wanted to get a consensus on this before I spend any time on rounding. Do we want to:

1. Round to the nearest _____th
2. Not round at all
3. Not round for this PR, but revisit later in a separate issue

Thanks guys! This and crosshairs are my focus for the day, which I will make sure I get shipped before I pivot to PRIOR, but if we don't have consensus before I roll off of AllenNLP then I will default to option 3.

On a related note, having a custom tooltip will allow us to include whatever metadata we want. Something to think about for future iterations.

**Comment by matt-gardner** [comment]
I'd probably default to no rounding.  These are often probability distributions, and some have very small values.  Rounding 0.0001 to 0 would be very bad, as those are very different values in a probability distribution (that is, seeing a 0 in a probability distribution typically means something is broken in my model, while 0.0001 is just fine).
