### ISSUE TITLE
demo.allennlp.org should support HTTPS/SSL

### ISSUE THREAD

**Issue by splittingfield** [allenai/allennlp-demo#98]
The motivation here is obvious.  Also, in general, supporting SSL is becoming viewed as "table stakes" for sites, even those that don't share private information. Chrome is now marking all sites that do not have SSL as insecure be default now as well and google uses HTTPS support within their rankings.

**Comment by schmmd** [comment]
Fixed as this was easy to do when I had to preserve requester IP addresses.

**Comment by splittingfield** [comment]
Although the demo supports SSL now, there is still work required to redirect HTTP -> HTTPS.

I could not find the yaml file for ingress, but I believe we want to make sure that the `nginx.ingress.kubernetes.io/ssl-redirect` is not set to false, which will lead to a proper 308 and redirect to TLS
