### ISSUE TITLE
Update Sentry and Filter Spurious Errors

### ISSUE THREAD

**Issue by codeviking** [allenai/allennlp-demo#997]
@mkusold recently updated our Sentry config for the AI2 website, as to ignore spurious errors that produce a lot of noise.

We should apply the same fix to the AllenNLP Demo. Here's the relevant PR:
https://github.com/allenai/ai2-web/pull/767

**Comment by mkusold** [comment]
@codeviking out of curiosity, are these two projects the only ones using Sentry? (I ask you because my Sentry only shows AI2-web so I don't have visibility on how many exist in total)
I'm trying to evaluate how common the need for these configs are.

**Comment by codeviking** [comment]
ReViz has two projects -- the ai2-website and the allennlp-demo.  I added the allennlp-demo project to the ReViz team, hopefully you can see it now.
